-- Roles for the application database.
--
-- Required psql vars (passed by DeployRdsWorker via psql -v):
--   app_user            CanopyDbUsername from CANOPY_AWS_PARAMETER_FILE
--   app_user_password   CanopyDbPassword from CANOPY_AWS_PARAMETER_FILE
--
-- Re-runnable: existing roles get their password rotated; missing roles are
-- created. Mirrors the pattern in 010_create_keycloak_db.sql.
--
-- canopy_admin is intentionally NOT parameterized — every per-table file
-- generated by pg_dump has `ALTER TABLE … OWNER TO canopy_admin`, so the
-- name has to stay literal across all installations. Nothing connects as
-- canopy_admin directly; the master user becomes a member of it via the
-- dynamic GRANT below so 600_grants.sql can `SET ROLE canopy_admin` when
-- applying ALTER DEFAULT PRIVILEGES.

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- canopy_admin (literal name, not parameterized)
-- ---------------------------------------------------------------------------
SELECT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'canopy_admin')::text
  AS canopy_admin_exists \gset

\if :canopy_admin_exists
  \echo 'canopy_admin already exists — leaving in place.'
\else
  \echo 'Creating canopy_admin…'
  CREATE ROLE canopy_admin WITH
    LOGIN
    PASSWORD 'REPLACEME'
    NOSUPERUSER
    INHERIT
    CREATEDB
    CREATEROLE
    NOREPLICATION;
\endif

GRANT rds_superuser TO canopy_admin WITH ADMIN OPTION;

-- The deploy runs as the RDS master user (e.g. canopi_postgres_<env>), which
-- needs to be a member of canopy_admin so 600_grants.sql can SET ROLE
-- canopy_admin to apply ALTER DEFAULT PRIVILEGES. Granted dynamically against
-- the connected user so this script doesn't hardcode the master-user name.
DO $$ BEGIN
  EXECUTE format('GRANT canopy_admin TO %I', current_user);
END $$;


-- ---------------------------------------------------------------------------
-- Application user (parameterized — name and password from psql -v).
-- Re-running this file rotates the password to whatever's in the param file,
-- so the role and the application secret never drift.
-- ---------------------------------------------------------------------------
SELECT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_user')::text
  AS app_user_exists \gset

\if :app_user_exists
  \echo 'Application user already exists — rotating password.'
  ALTER ROLE :"app_user" WITH LOGIN PASSWORD :'app_user_password';
\else
  \echo 'Creating application user…'
  CREATE ROLE :"app_user" WITH
    LOGIN
    PASSWORD :'app_user_password'
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    VALID UNTIL 'infinity';
\endif
