-- Data for Name: entity_property; Type: TABLE DATA; Schema: public; Owner: canopy_admin
--

-- INSERT INTO public.entity_property VALUES (1, 'phs', NULL, 1, 1, 2, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (2, 'title', NULL, 1, 1, 1, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (6, 'studystartdate', NULL, 1, 4, 2, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (7, 'studyenddate', NULL, 1, 4, 2, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (5, 'center', NULL, 1, 3, 2, false, false, 2, false);
INSERT INTO public.entity_property VALUES (20, 'source', NULL, 1, 3, 2, false, true, 3, false);
INSERT INTO public.entity_property VALUES (3, 'description', NULL, 1, 1, 1, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (9, 'multi_center_sites', NULL, 1, 1, 1, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (10, 'pi_name', NULL, 1, 1, 1, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (18, 'estimated_participants', NULL, 1, 2, 1, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (36, 'aggregate_appropriate_for_general_use', NULL, 1, 5, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (38, 'consent_to_add_aggregate', NULL, 1, 5, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (39, 'consent_to_add_individual', NULL, 1, 5, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (42, 'data_access_points', NULL, 1, 3, 1, false, true, 4, true);
INSERT INTO public.entity_property VALUES (43, 'data_analyses', NULL, 1, 3, 1, false, true, 5, true);
INSERT INTO public.entity_property VALUES (45, 'data_from_repository_name', NULL, 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (46, 'data_phenotype', NULL, 1, 3, 1, false, true, 10, true);
INSERT INTO public.entity_property VALUES (47, 'data_sample_collection', NULL, 1, 3, 1, false, true, 11, true);
INSERT INTO public.entity_property VALUES (48, 'data_sharing_info', NULL, 1, 5, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (50, 'data_storage_size', NULL, 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (51, 'data_submission_date', NULL, 1, 4, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (52, 'data_submission_method', NULL, 1, 3, 1, false, false, 13, true);
INSERT INTO public.entity_property VALUES (53, 'data_submission_timeline_details', NULL, 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (54, 'data_target_delivery_date', NULL, 1, 4, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (55, 'data_target_release_date', NULL, 1, 4, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (61, 'geno_seq_platform_info', NULL, 1, 6, 1, false, true, NULL, true);
INSERT INTO public.entity_property VALUES (62, 'geno_seq_platform_url', NULL, 1, 1, 1, false, true, NULL, true);
INSERT INTO public.entity_property VALUES (63, 'geno_seq_platform_probes', NULL, 1, 1, 1, false, true, NULL, true);
INSERT INTO public.entity_property VALUES (64, 'geno_seq_platform_vendor', NULL, 1, 1, 1, false, true, NULL, true);
INSERT INTO public.entity_property VALUES (65, 'geno_seq_platform_description', NULL, 1, 1, 1, false, true, NULL, true);
INSERT INTO public.entity_property VALUES (66, 'geno_seq_platform_name_version', NULL, 1, 1, 1, false, true, NULL, true);
INSERT INTO public.entity_property VALUES (68, 'has_era_account', NULL, 1, 5, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (69, 'has_ic', NULL, 1, 5, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (71, 'individual_appropriate_for_general_use', NULL, 1, 5, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (72, 'other_group_description', NULL, 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (26, 'data_general_types', NULL, 1, 3, 1, false, true, 19, false);
INSERT INTO public.entity_property VALUES (44, 'data_array_data', NULL, 1, 3, 1, false, true, 24, true);
INSERT INTO public.entity_property VALUES (24, 'institutes_supporting_study', NULL, 1, 3, 1, false, true, 18, false);
INSERT INTO public.entity_property VALUES (22, 'types', NULL, 1, 3, 1, false, true, 17, false);
INSERT INTO public.entity_property VALUES (35, 'acknowledgement_statement', NULL, 1, 1, 1, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (67, 'grant_number', NULL, 1, 1, 1, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (60, 'general_research_group', NULL, 1, 3, 1, false, true, 21, false);
INSERT INTO public.entity_property VALUES (70, 'health_biomed_group', NULL, 1, 3, 1, false, true, 22, false);
INSERT INTO public.entity_property VALUES (78, 'release_date', 'Date when study data was first made publicly available through RADx Data Hub', 1, 4, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (57, 'disease_specific_related_conditions', NULL, 1, 1, 1, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (49, 'data_species', NULL, 1, 3, 1, false, true, 12, false);
INSERT INTO public.entity_property VALUES (83, 'types_other_specify', 'Other type of study design, specify:', 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (91, 'data_analyses_other_specify', 'Other type of genomic analyses, specify:', 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (17, 'officer_sign_date', NULL, 1, 4, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (25, 'needs_institutional_certifications', NULL, 1, 5, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (11, 'pi_email', NULL, 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (12, 'pi_assistant_name', NULL, 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (13, 'pi_assistant_email', NULL, 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (15, 'pi_sign_date', NULL, 1, 4, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (16, 'po_name', NULL, 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (27, 'data_genomic', NULL, 1, 3, 1, false, true, 6, true);
INSERT INTO public.entity_property VALUES (28, 'data_genotype', NULL, 1, 3, 1, false, true, 7, true);
INSERT INTO public.entity_property VALUES (29, 'data_sample_types', NULL, 1, 3, 1, false, true, 8, true);
INSERT INTO public.entity_property VALUES (30, 'data_sequencing', NULL, 1, 3, 1, false, true, 9, true);
INSERT INTO public.entity_property VALUES (56, 'disease_specific_group', NULL, 1, 3, 1, false, true, 20, false);
INSERT INTO public.entity_property VALUES (58, 'eua', NULL, 1, 1, 4, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (76, 'has_data_files', 'Indicates whether the study has data files available for request', 1, 3, 3, false, false, 15, false);
INSERT INTO public.entity_property VALUES (77, 'actual_study_size', 'Size of the study (all data files) submitted to RADx Data Hub', 1, 2, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (80, 'study_version', 'The version number associated with the RADx Hub Online Submission ', 1, 2, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (59, 'expected_data_format', NULL, 1, 1, 4, false, true, NULL, true);
INSERT INTO public.entity_property VALUES (73, 'project_number', NULL, 1, 1, 4, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (40, 'controlled_access', NULL, 1, 5, 3, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (41, 'controlled_access_data', NULL, 1, 5, 3, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (79, 'updated_at', 'Date when the study was last updated in the RADx Hub Online Submission', 1, 4, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (32, 'data_policy_accepted', NULL, 1, 5, 3, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (33, 'reject_comments', NULL, 1, 1, 3, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (34, 'study_approved_date', NULL, 1, 4, 3, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (31, 'user_agreement_accepted', NULL, 1, 5, 3, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (37, 'awardee', NULL, 1, 1, 4, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (19, 'public_access_data', NULL, 1, 5, 3, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (23, 'unrestricted_access', NULL, 1, 5, 3, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (85, 'data_general_types_other_specify', 'Other general data types expected to be submitted for the study, specify', 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (86, 'data_genomic_other_specify', 'Other genomic data types expected to be submitted for the study, specify:', 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (87, 'data_phenotype_other_specify', 'Other Phenotype data types expected to be submitted for the study, specify:', 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (88, 'data_sample_types_other_specify', 'Other sample types expected to be submitted for the study, specify:', 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (89, 'data_genotype_other_specify', 'Other genotype data types expected to be submitted for the study, specify:', 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (90, 'data_sequencing_other_specify', 'Other sequencing data types expected to be submitted for the study, specify:', 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (92, 'data_array_data_other_specify', 'Other type of genomic array data, specify:', 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (84, 'source_other_specify', 'Other methods used to collect the data, or the type of data source that the data is derived from', 1, 1, 2, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (21, 'subject', NULL, 1, 1, 2, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (74, 'study_DOI', 'The Digital Object Identifier (DOI) assigned to the study', 1, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (100, 'FOA_number', 'Funding Opportunity Announcement (FOA) Number ', 1, 1, 2, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (101, 'FOA_URL', 'Funding Opportunity Announcement (FOA) URL', 1, 1, 2, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (95, 'study_website_URL', 'Study Website URL', 1, 1, 2, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (97, 'publication_URL', 'Primary Publication URL', 1, 1, 2, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (82, 'topics', 'Select the topics covered by the study', 1, 3, 2, false, true, 16, false);
INSERT INTO public.entity_property VALUES (98, 'access_type', NULL, 1, 3, 1, false, false, 23, true);
INSERT INTO public.entity_property VALUES (99, 'data_access_type', NULL, 1, 3, 1, false, true, 26, true);
INSERT INTO public.entity_property VALUES (102, 'estimated_participant_range', NULL, 1, 3, 2, false, false, 27, false);
INSERT INTO public.entity_property VALUES (14, 'pi_institution', NULL, 1, 1, 1, false, false, NULL, true);
INSERT INTO public.entity_property VALUES (93, 'data_access_points_other', 'Other data access point, list all', 1, 1, 1, false, true, NULL, true);
INSERT INTO public.entity_property VALUES (94, 'topics_other_specify', 'Other study topics, specify', 1, 1, 2, false, true, NULL, true);
INSERT INTO public.entity_property VALUES (96, 'CT_URL', 'ClinicalTrials.gov URL', 1, 1, 2, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (81, 'study_population_focus', NULL, 1, 3, 2, false, true, 28, false);
INSERT INTO public.entity_property VALUES (4, 'RAPIDS_link', NULL, 1, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (75, 'study_citation', 'Citation for citing the use of the study from RADx Data Hub. Principal Investigator (Publication Year). Study Name (Version) [Resource Type]. Publisher. Identifier', 1, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (103, 'data_use_limitations', 'Data use limitations based on the Consent Group Category (i.e., General Research Use, Health/Medical/Biomedical, Disease-Specific, or Other)', 1, 1, 2, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (8, 'is_multi_center', NULL, 1, 3, 1, false, false, 15, false);
INSERT INTO public.entity_property VALUES (200, 'variable_name', NULL, 2, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (201, 'variable_label', NULL, 2, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (204, 'variable_category', NULL, 2, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (205, 'variable_description', NULL, 2, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (206, 'variable_keywords', NULL, 2, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (207, 'variable_term', NULL, 2, 1, 3, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (208, 'variable_unit', NULL, 2, 1, 3, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (209, 'variable_cardinality', NULL, 2, 1, 3, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (210, 'variable_provenance', NULL, 2, 1, 3, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (211, 'variable_notes', NULL, 2, 1, 3, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (212, 'variable_mapping', NULL, 2, 1, 3, false, true, NULL, false);
INSERT INTO public.entity_property VALUES (202, 'section', NULL, 2, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (203, 'datatype', NULL, 2, 1, 3, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (214, 'study_name', NULL, 2, 1, 1, false, false, NULL, false);
INSERT INTO public.entity_property VALUES (104, 'study_variables', NULL, 1, 1, 3, false, true, NULL, NULL);


--
