-- Data for Name: lkup_property_codelist_value; Type: TABLE DATA; Schema: public; Owner: canopy_admin
--

INSERT INTO public.lkup_property_codelist_value VALUES (335, 3, 'Survey', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (336, 3, 'Interview or Focus Group', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (337, 3, 'Wearable', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (338, 3, 'Smartphone', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (339, 3, 'Contact Tracing', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (340, 3, 'Antigen Testing Device', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (344, 3, 'Chemosensory Testing Device', 100);
INSERT INTO public.lkup_property_codelist_value VALUES (345, 3, 'Electrochemical Testing Device', 110);
INSERT INTO public.lkup_property_codelist_value VALUES (346, 3, 'Unspecified COVID Testing Device', 120);
INSERT INTO public.lkup_property_codelist_value VALUES (347, 3, 'Wastewater Sampling', 130);
INSERT INTO public.lkup_property_codelist_value VALUES (348, 3, 'Disease Registry', 140);
INSERT INTO public.lkup_property_codelist_value VALUES (349, 3, 'Biobank Samples', 150);
INSERT INTO public.lkup_property_codelist_value VALUES (350, 3, 'Real-World Data', 160);
INSERT INTO public.lkup_property_codelist_value VALUES (351, 18, 'NIH CC', 260);
INSERT INTO public.lkup_property_codelist_value VALUES (341, 3, 'Molecular Nucleic Acid or PCR Testing Device', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (343, 3, 'Breath Analysis or Airborne Detection Device', 90);
INSERT INTO public.lkup_property_codelist_value VALUES (342, 3, 'Antibody or Adaptive Immune Response Testing', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (361, 19, 'Temporal', 290);
INSERT INTO public.lkup_property_codelist_value VALUES (356, 19, 'Chemosensor', 16);
INSERT INTO public.lkup_property_codelist_value VALUES (357, 19, 'Geospatial', 85);
INSERT INTO public.lkup_property_codelist_value VALUES (358, 19, 'Microscopy', 152);
INSERT INTO public.lkup_property_codelist_value VALUES (359, 19, 'Mobile', 154);
INSERT INTO public.lkup_property_codelist_value VALUES (360, 19, 'Sequencing', 195);
INSERT INTO public.lkup_property_codelist_value VALUES (362, 22, 'Health or Biomedical Purpose', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (355, 19, 'Biologic Specimens', 14);
INSERT INTO public.lkup_property_codelist_value VALUES (354, 19, 'Biosensor', 12);
INSERT INTO public.lkup_property_codelist_value VALUES (169, 23, 'Unrestricted', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (170, 23, 'Controlled', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (171, 26, 'Controlled Access Data', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (172, 26, 'Public Access Data', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (1, 15, 'Yes', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (352, 28, 'N/A', 180);
INSERT INTO public.lkup_property_codelist_value VALUES (29, 19, 'Environmental', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (309, 16, 'At-Home or Over-the-Counter (OTC) Self-Testing', 290);
INSERT INTO public.lkup_property_codelist_value VALUES (310, 16, 'Serological or Antibody Testing', 300);
INSERT INTO public.lkup_property_codelist_value VALUES (314, 16, 'Testing Rate or Uptake', 340);
INSERT INTO public.lkup_property_codelist_value VALUES (315, 16, 'Vaccination Rate or Uptake', 350);
INSERT INTO public.lkup_property_codelist_value VALUES (179, 27, '> 5000', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (180, 27, 'No Participants', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (133, 7, 'CNV calls from microarray', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (134, 7, 'Genotype calls derived from Sequence', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (135, 7, 'Non-human data', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (141, 9, 'Targeted Exome', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (136, 7, 'Somatic SNV (.MAF)', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (137, 7, 'Other', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (138, 9, '16S rRNA', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (139, 9, 'Epigenomic Marks', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (140, 9, 'Sanger', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (25, 19, 'Behavioral', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (26, 19, 'Clinical', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (27, 19, 'Cognitive', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (28, 19, 'Electronic Medical Records', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (30, 19, 'Family History', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (31, 19, 'Genomic', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (32, 19, 'Genotyping', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (142, 9, 'Targeted Genome', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (143, 9, 'Targeted Transcriptome', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (144, 9, 'Whole Exome', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (145, 9, 'Whole Genome', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (146, 9, 'Whole Transcriptome', 90);
INSERT INTO public.lkup_property_codelist_value VALUES (147, 9, 'Other', 100);
INSERT INTO public.lkup_property_codelist_value VALUES (148, 5, 'Array-derived Expression', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (149, 5, 'Array-derived Methylation', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (150, 5, 'Association/Linkage Results', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (151, 5, 'RNA Seq derived Expression', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (152, 5, 'Other', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (153, 24, 'Expression Array', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (154, 24, 'Methylation Array', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (155, 24, 'SNP Array', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (156, 24, 'Other', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (308, 16, 'Screening Testing', 280);
INSERT INTO public.lkup_property_codelist_value VALUES (311, 16, 'Seroprevalence', 310);
INSERT INTO public.lkup_property_codelist_value VALUES (312, 16, 'Social Determinants of Health', 320);
INSERT INTO public.lkup_property_codelist_value VALUES (313, 16, 'Substance Use', 330);
INSERT INTO public.lkup_property_codelist_value VALUES (316, 16, 'Variants', 360);
INSERT INTO public.lkup_property_codelist_value VALUES (317, 16, 'Virological Testing', 370);
INSERT INTO public.lkup_property_codelist_value VALUES (318, 16, 'Wastewater Surveillance', 380);
INSERT INTO public.lkup_property_codelist_value VALUES (319, 17, 'Case-Control', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (80, 13, 'date', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (81, 13, 'timeline', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (174, 27, '1 - 250', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (175, 27, '251 - 500', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (176, 27, '501 - 1000', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (177, 27, '1001 - 2000', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (178, 27, '2001 - 5000', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (181, 27, 'Unknown', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (320, 17, 'Clinical Genetic Testing', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (96, 20, 'Not-for-profit Organization', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (97, 20, 'Disease-Specific for COVID-19', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (86, 21, 'Not-for-profit Organization', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (53, 12, 'Human', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (54, 12, 'Non-Human', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (281, 16, 'Artificial Intelligence or Machine Learning', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (282, 16, 'Biosensor Technologies', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (296, 16, 'Medical Device or Tool Development', 160);
INSERT INTO public.lkup_property_codelist_value VALUES (304, 16, 'Novel Biosensing or VOC', 240);
INSERT INTO public.lkup_property_codelist_value VALUES (305, 16, 'Pandemic Perceptions or Decision-Making', 250);
INSERT INTO public.lkup_property_codelist_value VALUES (267, 28, 'Lower Socioeconomic Status (SES) Populations', 150);
INSERT INTO public.lkup_property_codelist_value VALUES (2, 15, 'No', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (3, 14, 'TRUE', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (4, 14, 'FALSE', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (5, 2, 'RADx DHT', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (6, 2, 'RADx-rad', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (7, 2, 'RADx Tech', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (8, 2, 'RADx-UP', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (363, 2, 'Stanford', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (284, 16, 'Community Outreach Programs', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (285, 16, 'Comorbidities', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (286, 16, 'COVID Hotspots', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (287, 16, 'COVID in School Settings', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (288, 16, 'COVID Testing Deserts', 85);
INSERT INTO public.lkup_property_codelist_value VALUES (289, 16, 'Diagnostic Testing', 90);
INSERT INTO public.lkup_property_codelist_value VALUES (290, 16, 'Digital Health Applications', 100);
INSERT INTO public.lkup_property_codelist_value VALUES (291, 16, 'Disease Surveillance', 110);
INSERT INTO public.lkup_property_codelist_value VALUES (292, 16, 'Health Behaviors', 120);
INSERT INTO public.lkup_property_codelist_value VALUES (293, 16, 'Immune Responses', 130);
INSERT INTO public.lkup_property_codelist_value VALUES (294, 16, 'Influenza', 140);
INSERT INTO public.lkup_property_codelist_value VALUES (295, 16, 'Long COVID', 150);
INSERT INTO public.lkup_property_codelist_value VALUES (297, 16, 'Mental Health', 170);
INSERT INTO public.lkup_property_codelist_value VALUES (298, 16, 'Mobile Unit Testing', 180);
INSERT INTO public.lkup_property_codelist_value VALUES (300, 16, 'Multimodal Surveillance', 200);
INSERT INTO public.lkup_property_codelist_value VALUES (301, 16, 'Multisystem Inflammatory Syndrome (MIS)', 210);
INSERT INTO public.lkup_property_codelist_value VALUES (302, 16, 'Multisystem Inflammatory Syndrome in Children (MIS-C)', 220);
INSERT INTO public.lkup_property_codelist_value VALUES (303, 16, 'Next Generation Sequencing (NGS)', 230);
INSERT INTO public.lkup_property_codelist_value VALUES (306, 16, 'Point-of-Care (POC) Testing', 260);
INSERT INTO public.lkup_property_codelist_value VALUES (307, 16, 'Rapid Diagnostic Test (RDT)', 270);
INSERT INTO public.lkup_property_codelist_value VALUES (55, 18, 'NCATS', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (56, 18, 'NCCIH', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (57, 18, 'NCI', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (58, 18, 'NDA', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (59, 18, 'NEI', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (60, 18, 'NHGRI', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (61, 18, 'NHLBI', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (62, 18, 'NIA', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (63, 18, 'NIAAA', 90);
INSERT INTO public.lkup_property_codelist_value VALUES (64, 18, 'NIAID', 100);
INSERT INTO public.lkup_property_codelist_value VALUES (65, 18, 'NIAMS', 110);
INSERT INTO public.lkup_property_codelist_value VALUES (66, 18, 'NIBIB', 120);
INSERT INTO public.lkup_property_codelist_value VALUES (67, 18, 'NICHD', 130);
INSERT INTO public.lkup_property_codelist_value VALUES (68, 18, 'NIDA', 140);
INSERT INTO public.lkup_property_codelist_value VALUES (69, 18, 'NIDCD', 150);
INSERT INTO public.lkup_property_codelist_value VALUES (70, 18, 'NIDCR', 160);
INSERT INTO public.lkup_property_codelist_value VALUES (71, 18, 'NIDDK', 170);
INSERT INTO public.lkup_property_codelist_value VALUES (72, 18, 'NIEHS', 180);
INSERT INTO public.lkup_property_codelist_value VALUES (73, 18, 'NIGMS', 190);
INSERT INTO public.lkup_property_codelist_value VALUES (74, 18, 'NIH OD', 200);
INSERT INTO public.lkup_property_codelist_value VALUES (75, 18, 'NIMH', 210);
INSERT INTO public.lkup_property_codelist_value VALUES (76, 18, 'NIMHD', 220);
INSERT INTO public.lkup_property_codelist_value VALUES (77, 18, 'NINDS', 230);
INSERT INTO public.lkup_property_codelist_value VALUES (78, 18, 'NINR', 240);
INSERT INTO public.lkup_property_codelist_value VALUES (79, 18, 'NLM', 250);
INSERT INTO public.lkup_property_codelist_value VALUES (83, 21, 'IRB approval required', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (84, 21, 'Publication required', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (85, 21, 'Collaboration required', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (88, 22, 'IRB approval required', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (89, 22, 'Publication required', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (90, 22, 'Collaboration required', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (91, 22, 'Not-for-profit use only', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (93, 20, 'IRB approval required', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (94, 20, 'Publication required', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (95, 20, 'Collaboration required', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (98, 4, 'RADx Data Hub', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (99, 4, 'Sequence Read Archive (SRA)', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (100, 4, 'Array Express', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (101, 4, 'ClinVar', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (102, 4, 'dbGaP', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (103, 4, 'dbVar', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (104, 4, 'dbSNP', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (105, 4, 'ENA', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (106, 4, 'GenBank', 90);
INSERT INTO public.lkup_property_codelist_value VALUES (107, 4, 'GEO', 100);
INSERT INTO public.lkup_property_codelist_value VALUES (108, 4, 'MGI', 110);
INSERT INTO public.lkup_property_codelist_value VALUES (109, 4, 'Trace Archive', 120);
INSERT INTO public.lkup_property_codelist_value VALUES (110, 4, 'Other', 130);
INSERT INTO public.lkup_property_codelist_value VALUES (111, 11, 'Prospective Sample', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (113, 6, 'Aggregate Data', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (114, 6, 'Individual-level Data', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (115, 6, 'Non-human Data', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (116, 6, 'Other', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (117, 10, 'Aggregate Data', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (118, 10, 'Individual-level Data', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (119, 10, 'Non-human Data', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (120, 10, 'Other', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (121, 8, 'DNA', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (122, 8, 'Germline', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (123, 8, 'Mitochondria', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (124, 8, 'Single Cell', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (125, 8, 'From Repository [free text]', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (126, 8, 'Microbiome', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (127, 8, 'RNA', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (128, 8, 'Tumor/Natural', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (129, 8, 'Other', 90);
INSERT INTO public.lkup_property_codelist_value VALUES (130, 7, 'Array CGH CNVs', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (131, 7, 'Array-derived Genotypes', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (132, 7, 'CNV calls derived from Sequencing', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (268, 28, 'Older Adults or Elderly', 160);
INSERT INTO public.lkup_property_codelist_value VALUES (269, 28, 'Adults', 170);
INSERT INTO public.lkup_property_codelist_value VALUES (33, 19, 'Imaging', 90);
INSERT INTO public.lkup_property_codelist_value VALUES (34, 19, 'Immunological', 100);
INSERT INTO public.lkup_property_codelist_value VALUES (35, 19, 'Individual Genotype', 110);
INSERT INTO public.lkup_property_codelist_value VALUES (36, 19, 'Individual Phenotype', 120);
INSERT INTO public.lkup_property_codelist_value VALUES (37, 19, 'Individual Sequencing', 130);
INSERT INTO public.lkup_property_codelist_value VALUES (38, 19, 'Metabolomic', 140);
INSERT INTO public.lkup_property_codelist_value VALUES (321, 17, 'Cross-Sectional', 30);
INSERT INTO public.lkup_property_codelist_value VALUES (326, 17, 'Longitudinal Cohort', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (329, 17, 'Mixed Methods', 110);
INSERT INTO public.lkup_property_codelist_value VALUES (330, 17, 'Observational', 120);
INSERT INTO public.lkup_property_codelist_value VALUES (331, 17, 'Open Cohort', 130);
INSERT INTO public.lkup_property_codelist_value VALUES (333, 17, 'Time-Series', 150);
INSERT INTO public.lkup_property_codelist_value VALUES (249, 28, 'Immigrants', 15);
INSERT INTO public.lkup_property_codelist_value VALUES (255, 28, 'Children', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (257, 28, 'Essential Workers', 77);
INSERT INTO public.lkup_property_codelist_value VALUES (263, 28, 'Dialysis Patients', 120);
INSERT INTO public.lkup_property_codelist_value VALUES (265, 28, 'Rural Communities', 140);
INSERT INTO public.lkup_property_codelist_value VALUES (39, 19, 'Metagenomic', 150);
INSERT INTO public.lkup_property_codelist_value VALUES (40, 19, 'Physical Activity', 160);
INSERT INTO public.lkup_property_codelist_value VALUES (41, 19, 'Proteomic', 170);
INSERT INTO public.lkup_property_codelist_value VALUES (42, 19, 'Psychological', 180);
INSERT INTO public.lkup_property_codelist_value VALUES (44, 19, 'Social', 200);
INSERT INTO public.lkup_property_codelist_value VALUES (45, 19, 'Supporting Documents', 210);
INSERT INTO public.lkup_property_codelist_value VALUES (112, 11, 'Existing (Legacy)', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (43, 19, 'Questionnaire or Survey', 190);
INSERT INTO public.lkup_property_codelist_value VALUES (46, 19, 'Other', 999);
INSERT INTO public.lkup_property_codelist_value VALUES (322, 17, 'Device Validation', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (323, 17, 'Device Verification', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (325, 17, 'Interventional or Clinical Trial', 70);
INSERT INTO public.lkup_property_codelist_value VALUES (248, 28, 'Racial or Ethnic Minorities', 10);
INSERT INTO public.lkup_property_codelist_value VALUES (250, 28, 'African Americans', 20);
INSERT INTO public.lkup_property_codelist_value VALUES (252, 28, 'Hispanics or Latinos', 40);
INSERT INTO public.lkup_property_codelist_value VALUES (253, 28, 'Native Hawaiians or Other Pacific Islanders', 50);
INSERT INTO public.lkup_property_codelist_value VALUES (254, 28, 'Asians', 60);
INSERT INTO public.lkup_property_codelist_value VALUES (256, 28, 'School Communities', 75);
INSERT INTO public.lkup_property_codelist_value VALUES (258, 28, 'Pregnant or Nursing Women', 80);
INSERT INTO public.lkup_property_codelist_value VALUES (259, 28, 'Intellectual or Developmental Disabilities', 90);
INSERT INTO public.lkup_property_codelist_value VALUES (260, 28, 'Homeless or Unhoused Populations', 100);
INSERT INTO public.lkup_property_codelist_value VALUES (261, 28, 'Incarcerated or Institutionalized Populations', 110);
INSERT INTO public.lkup_property_codelist_value VALUES (262, 28, 'People Living with HIV/AIDS', 115);
INSERT INTO public.lkup_property_codelist_value VALUES (264, 28, 'Sexual or Gender Minorities', 130);
INSERT INTO public.lkup_property_codelist_value VALUES (266, 28, 'Underserved or Vulnerable Populations', 145);


--
