-- Data for Name: entity_property_mta_mapping; Type: TABLE DATA; Schema: public; Owner: canopy_admin
--

INSERT INTO public.entity_property_mta_mapping VALUES (98, 44, 'SNP Array', 24, 155, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (99, 44, 'Other_Specify_3', 24, 156, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (101, 46, 'Aggregate Data', 10, 117, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (102, 46, 'Individuallevel Data', 10, 118, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (103, 46, 'NAno human data', 10, 119, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (104, 46, 'OtherPheno', 10, 120, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (105, 47, 'Prospective Sample', 11, 111, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (106, 47, 'Exisiting (Legacy)', 11, 112, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (1, 2, 'Study name', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (16, 98, 'unrestricted radio', 23, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (14, 99, 'Public Access Data', 26, 172, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (100, 45, 'Repository Name', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (15, 22, 'Study types eg collection longitudinal casecontrol case set control set parentoffspring trios cohort', 17, NULL, 'comma-separated');
INSERT INTO public.entity_property_mta_mapping VALUES (17, 24, 'NIH InstitutesCenters supporting the study', 18, NULL, 'comma-separated');
INSERT INTO public.entity_property_mta_mapping VALUES (111, 51, 'Date6_af_date', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (107, 48, 'NHGRI Genomic Data Sharing  Submission Information', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (110, 50, 'Number of bytes of data to be deposited', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (112, 52, 'Data submission radio', 13, 80, 'generation');
INSERT INTO public.entity_property_mta_mapping VALUES (113, 53, 'batch submission description', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (114, 52, 'Data submission radio', 13, 81, 'publication');
INSERT INTO public.entity_property_mta_mapping VALUES (115, 54, 'delivery date', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (116, 55, 'release date', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (2, 3, 'Original description', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (3, 8, 'Multisite radio', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (4, 9, 'Multicenter list', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (6, 11, 'PI email', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (7, 12, 'PI assistantsubmitter name', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (8, 13, 'PI assistantsubmitter email', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (9, 14, 'PI institution and branch', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (10, 15, 'Date1_af_date', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (11, 16, 'NIH Program Officer', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (12, 17, 'Date2_af_date', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (13, 18, 'Estimated number of study participants', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (18, 25, 'Institutional Certifications', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (108, 49, 'Human Data', 12, 53, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (109, 49, 'NonHuman Data', 12, 54, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (117, 56, 'DS Collab', 20, 95, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (118, 56, 'DS IRB', 20, 93, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (19, 26, 'Behavioral', 19, 25, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (20, 26, 'Clinical', 19, 26, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (21, 26, 'Coginitive', 19, 27, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (22, 26, 'Electronic Medical Records', 19, 28, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (24, 26, 'Family History', 19, 30, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (40, 26, 'Other (specify)', 19, 46, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (23, 26, 'Enviornmental (Physical)', 19, 29, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (25, 26, 'Genomic', 19, 31, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (26, 26, 'Genotyping', 19, 32, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (27, 26, 'Imaging', 19, 33, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (28, 26, 'Immunological', 19, 34, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (29, 26, 'IG', 19, 35, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (30, 26, 'IP', 19, 36, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (31, 26, 'IS', 19, 37, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (32, 26, 'Metabolomic', 19, 38, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (33, 26, 'Metagenomic', 19, 39, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (34, 26, 'Physical Activity', 19, 40, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (35, 26, 'Proteomic', 19, 41, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (36, 26, 'Psychological Variables', 19, 42, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (37, 26, 'Questionnaires/Surveys', 19, 43, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (38, 26, 'Social Variables', 19, 44, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (39, 26, 'Supporting Documents', 19, 45, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (41, 27, 'Genomic Aggregate Data', 6, 113, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (42, 27, 'Genomic Individuallevel Data', 6, 114, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (43, 27, 'Genomic NAno human data', 6, 115, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (44, 27, 'OtherGeno', 6, 116, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (45, 28, 'Array CGH CNVs', 7, 130, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (46, 28, 'Array-derived Genotypes', 7, 131, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (47, 28, 'CNV calls derived from', 7, 132, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (48, 28, 'CNV calls from', 7, 133, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (49, 28, 'Genotype calls derived from Sequence', 7, 134, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (50, 28, 'Genotype Non-Human Data', 7, 135, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (51, 28, 'Somatic SNV MAF', 7, 136, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (52, 28, 'Other_Specify_5', 7, 137, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (53, 29, 'DNA', 8, 121, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (77, 99, 'Controlled Access Data', 26, 171, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (72, 35, 'Acknowledgment Statement', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (73, 36, 'aggregate level radio', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (74, 38, 'aggregate collect radio', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (75, 39, 'individual collection radio', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (5, 10, 'PI name', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (54, 29, 'Germline', 8, 122, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (55, 29, 'Mitochondria', 8, 123, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (56, 29, 'Single Cell', 8, 124, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (57, 29, 'From Repository', 8, 125, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (58, 29, 'Microbiome', 8, 126, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (59, 29, 'RNA', 8, 127, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (60, 29, 'TumorNatural', 8, 128, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (61, 29, 'Other_Specify_2', 8, 129, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (62, 30, '16S rRNA', 9, 138, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (63, 30, 'Epigenomic Marks', 9, 139, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (64, 30, 'Sanger', 9, 140, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (65, 30, 'Targeted Exome', 9, 141, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (66, 30, 'Targeted Genome', 9, 142, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (67, 30, 'Targeted Transcriptome', 9, 143, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (68, 30, 'Whole Exome', 9, 144, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (69, 30, 'Whole Genome', 9, 145, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (70, 30, 'Whole Transcriptome', 9, 146, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (71, 30, 'Other_Specify_6', 9, 147, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (80, 42, 'Array Express', 4, 100, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (81, 42, 'ClinVar', 4, 101, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (82, 42, 'dbGaP', 4, 102, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (83, 42, 'dbVar', 4, 103, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (84, 42, 'dbSNP', 4, 104, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (85, 42, 'ENA', 4, 105, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (86, 42, 'GenBank', 4, 106, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (87, 42, 'GEO', 4, 107, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (88, 42, 'MGI', 4, 108, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (89, 42, 'Trace Archive', 4, 109, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (90, 42, 'Other list all', 4, 110, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (91, 43, 'Array derived Expression', 5, 148, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (92, 43, 'Array derived Methylatio', 5, 149, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (93, 43, 'AssociationLinkage Results', 5, 150, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (94, 43, 'RNA Seq derived', 5, 151, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (95, 43, 'Other_specify_4', 5, 152, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (96, 44, 'Expression Array', 24, 153, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (97, 44, 'Methylation Array', 24, 154, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (119, 56, 'DS NPU', 20, 96, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (120, 56, 'DS PUB', 20, 94, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (123, 60, 'GRU Collab', 21, 85, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (124, 60, 'GRU IRB', 21, 83, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (125, 60, 'GRU NPU', 21, 86, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (126, 60, 'GRU PUB', 21, 84, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (140, 70, 'HMB IRB', 22, 88, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (141, 70, 'HMB PUB', 22, 89, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (143, 70, 'HMB Collab', 22, 90, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (145, 70, 'HMB NPU', 22, 91, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (146, 83, 'Study types eg collection longitudinal casecontrol case set control set parentoffspring trios cohort', NULL, NULL, 'comma-separated');
INSERT INTO public.entity_property_mta_mapping VALUES (121, 56, 'DS Related Conditions', 20, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (122, 57, 'Use of data includes disease XX and related conditions describe and include examples', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (127, 62, 'URL 1', NULL, NULL, 'value_index 0');
INSERT INTO public.entity_property_mta_mapping VALUES (128, 63, 'Probe count 1', NULL, NULL, 'value_index 0');
INSERT INTO public.entity_property_mta_mapping VALUES (129, 64, 'Vendor 1', NULL, NULL, 'value_index 0');
INSERT INTO public.entity_property_mta_mapping VALUES (130, 65, 'Description 1', NULL, NULL, 'value_index 0');
INSERT INTO public.entity_property_mta_mapping VALUES (131, 66, 'Name and version 1', NULL, NULL, 'value_index 0');
INSERT INTO public.entity_property_mta_mapping VALUES (132, 62, 'URL 3', NULL, NULL, 'value_index 1');
INSERT INTO public.entity_property_mta_mapping VALUES (133, 63, 'Probe count 3', NULL, NULL, 'value_index 1');
INSERT INTO public.entity_property_mta_mapping VALUES (134, 64, 'Vendor 3', NULL, NULL, 'value_index 1');
INSERT INTO public.entity_property_mta_mapping VALUES (135, 65, 'Description 3', NULL, NULL, 'value_index 1');
INSERT INTO public.entity_property_mta_mapping VALUES (136, 66, 'Name and version 3', NULL, NULL, 'value_index 1');
INSERT INTO public.entity_property_mta_mapping VALUES (137, 67, 'NIH Grant or Contract Number', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (138, 68, 'eRA radio', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (139, 69, 'IC radio', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (142, 71, 'individual level radio', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (144, 72, 'Other describe', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (147, 85, 'General other', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (148, 86, 'Genomic Other', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (149, 87, 'Phenotype Other', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (150, 88, 'Sample type other', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (151, 89, 'Genotype other', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (152, 90, 'Sequencing other', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (153, 91, 'Analyses Other', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (154, 92, 'Array Data Other', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (155, 93, '1', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (156, 93, '2', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (157, 93, '3', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (158, 93, '4', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (159, 93, '5', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (160, 93, '6', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (161, 93, '7', NULL, NULL, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (78, 42, 'Sequence Read Archive SRA', 4, 98, NULL);
INSERT INTO public.entity_property_mta_mapping VALUES (79, 42, 'Trusted Partner eg Bionimbus GDC', 4, 99, NULL);


--
