-- Data for Name: lkup_country; Type: TABLE DATA; Schema: public; Owner: canopy_admin
--

INSERT INTO public.lkup_country VALUES (1, 'United States', 1);
INSERT INTO public.lkup_country VALUES (2, 'American Samoa', 2);
INSERT INTO public.lkup_country VALUES (3, 'Guam', 3);
INSERT INTO public.lkup_country VALUES (4, 'Northern Mariana Islands', 4);
INSERT INTO public.lkup_country VALUES (5, 'Puerto Rico', 5);
INSERT INTO public.lkup_country VALUES (6, 'U.S. Virgin Islands', 6);
INSERT INTO public.lkup_country VALUES (7, 'Afghanistan', 7);
INSERT INTO public.lkup_country VALUES (8, 'Albania', 8);
INSERT INTO public.lkup_country VALUES (9, 'Algeria', 9);
INSERT INTO public.lkup_country VALUES (10, 'Andorra', 10);
INSERT INTO public.lkup_country VALUES (11, 'Angola', 11);
INSERT INTO public.lkup_country VALUES (12, 'Antigua and Barbuda', 12);
INSERT INTO public.lkup_country VALUES (13, 'Argentina', 13);
INSERT INTO public.lkup_country VALUES (14, 'Armenia', 14);
INSERT INTO public.lkup_country VALUES (15, 'Australia', 15);
INSERT INTO public.lkup_country VALUES (16, 'Austria', 16);
INSERT INTO public.lkup_country VALUES (17, 'Azerbaijan', 17);
INSERT INTO public.lkup_country VALUES (18, 'Bahamas', 18);
INSERT INTO public.lkup_country VALUES (19, 'Bahrain', 19);
INSERT INTO public.lkup_country VALUES (20, 'Bangladesh', 20);
INSERT INTO public.lkup_country VALUES (21, 'Barbados', 21);
INSERT INTO public.lkup_country VALUES (22, 'Belarus', 22);
INSERT INTO public.lkup_country VALUES (23, 'Belgium', 23);
INSERT INTO public.lkup_country VALUES (24, 'Belize', 24);
INSERT INTO public.lkup_country VALUES (25, 'Benin', 25);
INSERT INTO public.lkup_country VALUES (26, 'Bhutan', 26);
INSERT INTO public.lkup_country VALUES (27, 'Bolivia', 27);
INSERT INTO public.lkup_country VALUES (28, 'Bosnia and Herzegovina', 28);
INSERT INTO public.lkup_country VALUES (29, 'Botswana', 29);
INSERT INTO public.lkup_country VALUES (30, 'Brazil', 30);
INSERT INTO public.lkup_country VALUES (31, 'Brunei', 31);
INSERT INTO public.lkup_country VALUES (32, 'Bulgaria', 32);
INSERT INTO public.lkup_country VALUES (33, 'Burkina Faso', 33);
INSERT INTO public.lkup_country VALUES (34, 'Burma', 34);
INSERT INTO public.lkup_country VALUES (35, 'Burundi', 35);
INSERT INTO public.lkup_country VALUES (36, 'Cabo Verde', 36);
INSERT INTO public.lkup_country VALUES (37, 'Cambodia', 37);
INSERT INTO public.lkup_country VALUES (38, 'Cameroon', 38);
INSERT INTO public.lkup_country VALUES (39, 'Canada', 39);
INSERT INTO public.lkup_country VALUES (40, 'Central African Republic', 40);
INSERT INTO public.lkup_country VALUES (41, 'Chad', 41);
INSERT INTO public.lkup_country VALUES (42, 'Chile', 42);
INSERT INTO public.lkup_country VALUES (43, 'China', 43);
INSERT INTO public.lkup_country VALUES (44, 'Colombia', 44);
INSERT INTO public.lkup_country VALUES (45, 'Comoros', 45);
INSERT INTO public.lkup_country VALUES (46, 'Congo (Brazzaville)', 46);
INSERT INTO public.lkup_country VALUES (47, 'Congo (Kinshasa)', 47);
INSERT INTO public.lkup_country VALUES (48, 'Costa Rica', 48);
INSERT INTO public.lkup_country VALUES (49, 'Côte d''Ivoire', 49);
INSERT INTO public.lkup_country VALUES (50, 'Croatia', 50);
INSERT INTO public.lkup_country VALUES (51, 'Cuba', 51);
INSERT INTO public.lkup_country VALUES (52, 'Cyprus', 52);
INSERT INTO public.lkup_country VALUES (53, 'Czech Republic', 53);
INSERT INTO public.lkup_country VALUES (54, 'Denmark', 54);
INSERT INTO public.lkup_country VALUES (55, 'Djibouti', 55);
INSERT INTO public.lkup_country VALUES (56, 'Dominica', 56);
INSERT INTO public.lkup_country VALUES (57, 'Dominican Republic', 57);
INSERT INTO public.lkup_country VALUES (58, 'Ecuador', 58);
INSERT INTO public.lkup_country VALUES (59, 'Egypt', 59);
INSERT INTO public.lkup_country VALUES (60, 'El Salvador', 60);
INSERT INTO public.lkup_country VALUES (61, 'Equatorial Guinea', 61);
INSERT INTO public.lkup_country VALUES (62, 'Eritrea', 62);
INSERT INTO public.lkup_country VALUES (63, 'Estonia', 63);
INSERT INTO public.lkup_country VALUES (64, 'Ethiopia', 64);
INSERT INTO public.lkup_country VALUES (65, 'Fiji', 65);
INSERT INTO public.lkup_country VALUES (66, 'Finland', 66);
INSERT INTO public.lkup_country VALUES (67, 'France', 67);
INSERT INTO public.lkup_country VALUES (68, 'Gabon', 68);
INSERT INTO public.lkup_country VALUES (69, 'Gambia', 69);
INSERT INTO public.lkup_country VALUES (70, 'Georgia', 70);
INSERT INTO public.lkup_country VALUES (71, 'Germany', 71);
INSERT INTO public.lkup_country VALUES (72, 'Ghana', 72);
INSERT INTO public.lkup_country VALUES (73, 'Greece', 73);
INSERT INTO public.lkup_country VALUES (74, 'Grenada', 74);
INSERT INTO public.lkup_country VALUES (75, 'Guatemala', 75);
INSERT INTO public.lkup_country VALUES (76, 'Guinea', 76);
INSERT INTO public.lkup_country VALUES (77, 'Guinea-Bissau', 77);
INSERT INTO public.lkup_country VALUES (78, 'Guyana', 78);
INSERT INTO public.lkup_country VALUES (79, 'Haiti', 79);
INSERT INTO public.lkup_country VALUES (80, 'Holy See', 80);
INSERT INTO public.lkup_country VALUES (81, 'Honduras', 81);
INSERT INTO public.lkup_country VALUES (82, 'Hungary', 82);
INSERT INTO public.lkup_country VALUES (83, 'Iceland', 83);
INSERT INTO public.lkup_country VALUES (84, 'India', 84);
INSERT INTO public.lkup_country VALUES (85, 'Indonesia', 85);
INSERT INTO public.lkup_country VALUES (86, 'Iran', 86);
INSERT INTO public.lkup_country VALUES (87, 'Iraq', 87);
INSERT INTO public.lkup_country VALUES (88, 'Ireland', 88);
INSERT INTO public.lkup_country VALUES (89, 'Israel', 89);
INSERT INTO public.lkup_country VALUES (90, 'Italy', 90);
INSERT INTO public.lkup_country VALUES (91, 'Jamaica', 91);
INSERT INTO public.lkup_country VALUES (92, 'Japan', 92);
INSERT INTO public.lkup_country VALUES (93, 'Jordan', 93);
INSERT INTO public.lkup_country VALUES (94, 'Kazakhstan', 94);
INSERT INTO public.lkup_country VALUES (95, 'Kenya', 95);
INSERT INTO public.lkup_country VALUES (96, 'Kiribati', 96);
INSERT INTO public.lkup_country VALUES (97, 'Korea, North', 97);
INSERT INTO public.lkup_country VALUES (98, 'Korea, South', 98);
INSERT INTO public.lkup_country VALUES (99, 'Kosovo', 99);
INSERT INTO public.lkup_country VALUES (100, 'Kuwait', 100);
INSERT INTO public.lkup_country VALUES (101, 'Kyrgyzstan', 101);
INSERT INTO public.lkup_country VALUES (102, 'Laos', 102);
INSERT INTO public.lkup_country VALUES (103, 'Latvia', 103);
INSERT INTO public.lkup_country VALUES (104, 'Lebanon', 104);
INSERT INTO public.lkup_country VALUES (105, 'Lesotho', 105);
INSERT INTO public.lkup_country VALUES (106, 'Liberia', 106);
INSERT INTO public.lkup_country VALUES (107, 'Libya', 107);
INSERT INTO public.lkup_country VALUES (108, 'Liechtenstein', 108);
INSERT INTO public.lkup_country VALUES (109, 'Lithuania', 109);
INSERT INTO public.lkup_country VALUES (110, 'Luxembourg', 110);
INSERT INTO public.lkup_country VALUES (111, 'Macedonia', 111);
INSERT INTO public.lkup_country VALUES (112, 'Madagascar', 112);
INSERT INTO public.lkup_country VALUES (113, 'Malawi', 113);
INSERT INTO public.lkup_country VALUES (114, 'Malaysia', 114);
INSERT INTO public.lkup_country VALUES (115, 'Maldives', 115);
INSERT INTO public.lkup_country VALUES (116, 'Mali', 116);
INSERT INTO public.lkup_country VALUES (117, 'Malta', 117);
INSERT INTO public.lkup_country VALUES (118, 'Marshall Islands', 118);
INSERT INTO public.lkup_country VALUES (119, 'Mauritania', 119);
INSERT INTO public.lkup_country VALUES (120, 'Mauritius', 120);
INSERT INTO public.lkup_country VALUES (121, 'Mexico', 121);
INSERT INTO public.lkup_country VALUES (122, 'Micronesia', 122);
INSERT INTO public.lkup_country VALUES (123, 'Moldova', 123);
INSERT INTO public.lkup_country VALUES (124, 'Monaco', 124);
INSERT INTO public.lkup_country VALUES (125, 'Mongolia', 125);
INSERT INTO public.lkup_country VALUES (126, 'Montenegro', 126);
INSERT INTO public.lkup_country VALUES (127, 'Morocco', 127);
INSERT INTO public.lkup_country VALUES (128, 'Mozambique', 128);
INSERT INTO public.lkup_country VALUES (129, 'Namibia', 129);
INSERT INTO public.lkup_country VALUES (130, 'Nauru', 130);
INSERT INTO public.lkup_country VALUES (131, 'Nepal', 131);
INSERT INTO public.lkup_country VALUES (132, 'Netherlands', 132);
INSERT INTO public.lkup_country VALUES (133, 'New Zealand', 133);
INSERT INTO public.lkup_country VALUES (134, 'Nicaragua', 134);
INSERT INTO public.lkup_country VALUES (135, 'Niger', 135);
INSERT INTO public.lkup_country VALUES (136, 'Nigeria', 136);
INSERT INTO public.lkup_country VALUES (137, 'Norway', 137);
INSERT INTO public.lkup_country VALUES (138, 'Oman', 138);
INSERT INTO public.lkup_country VALUES (139, 'Pakistan', 139);
INSERT INTO public.lkup_country VALUES (140, 'Palau', 140);
INSERT INTO public.lkup_country VALUES (141, 'Panama', 141);
INSERT INTO public.lkup_country VALUES (142, 'Papua New Guinea', 142);
INSERT INTO public.lkup_country VALUES (143, 'Paraguay', 143);
INSERT INTO public.lkup_country VALUES (144, 'Peru', 144);
INSERT INTO public.lkup_country VALUES (145, 'Philippines', 145);
INSERT INTO public.lkup_country VALUES (146, 'Poland', 146);
INSERT INTO public.lkup_country VALUES (147, 'Portugal', 147);
INSERT INTO public.lkup_country VALUES (148, 'Qatar', 148);
INSERT INTO public.lkup_country VALUES (149, 'Romania', 149);
INSERT INTO public.lkup_country VALUES (150, 'Russia', 150);
INSERT INTO public.lkup_country VALUES (151, 'Rwanda', 151);
INSERT INTO public.lkup_country VALUES (152, 'Saint Kitts and Nevis', 152);
INSERT INTO public.lkup_country VALUES (153, 'Saint Lucia', 153);
INSERT INTO public.lkup_country VALUES (154, 'Saint Vincent and the Grenadines', 154);
INSERT INTO public.lkup_country VALUES (155, 'Samoa', 155);
INSERT INTO public.lkup_country VALUES (156, 'San Marino', 156);
INSERT INTO public.lkup_country VALUES (157, 'Sao Tome and Principe', 157);
INSERT INTO public.lkup_country VALUES (158, 'Saudi Arabia', 158);
INSERT INTO public.lkup_country VALUES (159, 'Senegal', 159);
INSERT INTO public.lkup_country VALUES (160, 'Serbia', 160);
INSERT INTO public.lkup_country VALUES (161, 'Seychelles', 161);
INSERT INTO public.lkup_country VALUES (162, 'Sierra Leone', 162);
INSERT INTO public.lkup_country VALUES (163, 'Singapore', 163);
INSERT INTO public.lkup_country VALUES (164, 'Slovakia', 164);
INSERT INTO public.lkup_country VALUES (165, 'Slovenia', 165);
INSERT INTO public.lkup_country VALUES (166, 'Solomon Islands', 166);
INSERT INTO public.lkup_country VALUES (167, 'Somalia', 167);
INSERT INTO public.lkup_country VALUES (168, 'South Africa', 168);
INSERT INTO public.lkup_country VALUES (169, 'South Sudan', 169);
INSERT INTO public.lkup_country VALUES (170, 'Spain', 170);
INSERT INTO public.lkup_country VALUES (171, 'Sri Lanka', 171);
INSERT INTO public.lkup_country VALUES (172, 'Sudan', 172);
INSERT INTO public.lkup_country VALUES (173, 'Suriname', 173);
INSERT INTO public.lkup_country VALUES (174, 'Swaziland', 174);
INSERT INTO public.lkup_country VALUES (175, 'Sweden', 175);
INSERT INTO public.lkup_country VALUES (176, 'Switzerland', 176);
INSERT INTO public.lkup_country VALUES (177, 'Syria', 177);
INSERT INTO public.lkup_country VALUES (178, 'Tajikistan', 178);
INSERT INTO public.lkup_country VALUES (179, 'Tanzania', 179);
INSERT INTO public.lkup_country VALUES (180, 'Thailand', 180);
INSERT INTO public.lkup_country VALUES (181, 'Timor-Leste', 181);
INSERT INTO public.lkup_country VALUES (182, 'Togo', 182);
INSERT INTO public.lkup_country VALUES (183, 'Tonga', 183);
INSERT INTO public.lkup_country VALUES (184, 'Trinidad and Tobago', 184);
INSERT INTO public.lkup_country VALUES (185, 'Tunisia', 185);
INSERT INTO public.lkup_country VALUES (186, 'Turkey', 186);
INSERT INTO public.lkup_country VALUES (187, 'Turkmenistan', 187);
INSERT INTO public.lkup_country VALUES (188, 'Tuvalu', 188);
INSERT INTO public.lkup_country VALUES (189, 'Uganda', 189);
INSERT INTO public.lkup_country VALUES (190, 'Ukraine', 190);
INSERT INTO public.lkup_country VALUES (191, 'United Arab Emirates', 191);
INSERT INTO public.lkup_country VALUES (192, 'United Kingdom', 192);
INSERT INTO public.lkup_country VALUES (193, 'Uruguay', 193);
INSERT INTO public.lkup_country VALUES (194, 'Uzbekistan', 194);
INSERT INTO public.lkup_country VALUES (195, 'Vanuatu', 195);
INSERT INTO public.lkup_country VALUES (196, 'Venezuela', 196);
INSERT INTO public.lkup_country VALUES (197, 'Vietnam', 197);
INSERT INTO public.lkup_country VALUES (198, 'Yemen', 198);
INSERT INTO public.lkup_country VALUES (199, 'Zambia', 199);
INSERT INTO public.lkup_country VALUES (200, 'Zimbabwe', 200);


--
