-- Data for Name: lkup_core_variable_permissible_value; Type: TABLE DATA; Schema: public; Owner: canopy_admin
--

INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (1, 'nih_arthritis', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (2, 'nih_arthritis', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (3, 'nih_arthritis', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (4, 'nih_arthritis', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (5, 'nih_arthritis', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (6, 'nih_race', 0, 'American Indian or Alaska Native');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (7, 'nih_race', 1, 'Black or African American');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (8, 'nih_race', 2, 'Asian');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (9, 'nih_race', 3, 'Native Hawaiian or Other Pacific Islander');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (10, 'nih_race', 4, 'White');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (11, 'nih_race', 5, 'Middle Eastern or North African');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (12, 'nih_race', 6, 'Two or more races');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (13, 'nih_race', 97, 'Some other race');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (14, 'nih_race', 98, 'Do not know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (15, 'nih_race', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (16, 'nih_ethnicity', 0, 'No, not of Hispanic or Latino origin');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (17, 'nih_ethnicity', 1, 'Yes, of Hispanic or Latino origin');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (18, 'nih_ethnicity', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (19, 'nih_ethnicity', 98, 'Don''t Know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (20, 'nih_ethnicity', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (21, 'nih_sex', 0, 'Female');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (22, 'nih_sex', 1, 'Male');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (23, 'nih_sex', 2, 'Intersex');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (24, 'nih_sex', 3, 'Non-binary');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (25, 'nih_sex', 96, 'None of these describe me');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (26, 'nih_sex', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (27, 'nih_education', 0, 'Have never gone to school');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (28, 'nih_education', 1, 'Some school (Includes any education received below highschool graduate level)');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (29, 'nih_education', 2, 'High school graduate or GED completed');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (30, 'nih_education', 3, 'Some college (graduated or not) associates degree,technical degree,or vocational degree');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (31, 'nih_education', 4, 'Bachelor''s degree');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (32, 'nih_education', 5, 'Other advanced degree (Master''s,Doctorate or Professional Doctorate)');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (33, 'nih_education', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (34, 'nih_education', 98, 'Don''t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (35, 'nih_education', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (36, 'nih_employment', 0, 'Yes - Employed');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (37, 'nih_employment', 1, 'No - Not Employed');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (38, 'nih_employment', 2, 'Student');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (39, 'nih_employment', 3, 'Keeping household');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (40, 'nih_employment', 4, 'Retired');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (41, 'nih_employment', 5, 'Disabled or government support');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (42, 'nih_employment', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (43, 'nih_employment', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (44, 'nih_employment', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (45, 'nih_insurance', 0, 'None');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (46, 'nih_insurance', 1, 'Private');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (47, 'nih_insurance', 2, 'Public');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (48, 'nih_insurance', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (49, 'nih_insurance', 98, 'Don''t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (50, 'nih_insurance', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (51, 'nih_disability', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (52, 'nih_disability', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (53, 'nih_disability', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (54, 'nih_disability', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (55, 'nih_disability', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (56, 'nih_deaf', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (57, 'nih_deaf', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (58, 'nih_deaf', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (59, 'nih_deaf', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (60, 'nih_deaf', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (61, 'nih_lifetime_use_alcohol', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (62, 'nih_lifetime_use_alcohol', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (63, 'nih_lifetime_use_alcohol', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (64, 'nih_lifetime_use_alcohol', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (65, 'nih_lifetime_use_alcohol', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (66, 'nih_blind', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (67, 'nih_blind', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (68, 'nih_blind', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (69, 'nih_blind', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (70, 'nih_blind', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (71, 'nih_memory', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (72, 'nih_memory', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (73, 'nih_memory', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (74, 'nih_memory', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (75, 'nih_memory', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (76, 'nih_walk_climb', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (77, 'nih_walk_climb', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (78, 'nih_walk_climb', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (79, 'nih_walk_climb', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (80, 'nih_walk_climb', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (81, 'nih_dress_bathe', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (82, 'nih_dress_bathe', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (83, 'nih_dress_bathe', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (84, 'nih_dress_bathe', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (85, 'nih_dress_bathe', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (86, 'nih_errand', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (87, 'nih_errand', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (88, 'nih_errand', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (89, 'nih_errand', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (90, 'nih_errand', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (91, 'nih_af', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (92, 'nih_af', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (93, 'nih_af', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (94, 'nih_af', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (95, 'nih_af', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (96, 'nih_vaping_yn', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (97, 'nih_vaping_yn', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (98, 'nih_vaping_yn', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (99, 'nih_vaping_yn', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (100, 'nih_vaping_yn', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (101, 'nih_nicotine_yn', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (102, 'nih_nicotine_yn', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (103, 'nih_nicotine_yn', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (104, 'nih_nicotine_yn', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (105, 'nih_nicotine_yn', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (106, 'nih_vape_freq', 0, 'Not at all');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (107, 'nih_vape_freq', 1, 'Rarely');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (108, 'nih_vape_freq', 2, 'Some Days');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (109, 'nih_vape_freq', 3, 'Every Day');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (110, 'nih_vape_freq', 98, 'Don''t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (111, 'nih_vape_freq', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (112, 'nih_cig_smoke_freq', 0, 'Not at all');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (113, 'nih_cig_smoke_freq', 1, 'Rarely');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (114, 'nih_cig_smoke_freq', 2, 'Some Days');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (115, 'nih_cig_smoke_freq', 3, 'Every Day');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (116, 'nih_cig_smoke_freq', 98, 'Don''t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (117, 'nih_cig_smoke_freq', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (118, 'nih_smoking_yn', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (119, 'nih_smoking_yn', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (120, 'nih_smoking_yn', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (121, 'nih_smoking_yn', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (122, 'nih_smoking_yn', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (123, 'nih_history_smoking', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (124, 'nih_history_smoking', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (125, 'nih_history_smoking', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (126, 'nih_history_smoking', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (127, 'nih_history_smoking', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (128, 'nih_tobacco', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (129, 'nih_tobacco', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (130, 'nih_tobacco', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (131, 'nih_tobacco', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (132, 'nih_tobacco', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (133, 'nih_alcohol_yn', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (134, 'nih_alcohol_yn', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (135, 'nih_alcohol_yn', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (136, 'nih_alcohol_yn', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (137, 'nih_alcohol_yn', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (138, 'nih_alcohol_yrs', 0, 'Never');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (139, 'nih_alcohol_yrs', 1, 'Monthly Or Less');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (140, 'nih_alcohol_yrs', 2, 'Two To Four Times Per Month');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (141, 'nih_alcohol_yrs', 3, 'Two To Three Times Per Week');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (142, 'nih_alcohol_yrs', 4, 'Four Or More Times Per Week');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (143, 'nih_alcohol_yrs', 98, 'Don''t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (144, 'nih_alcohol_yrs', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (145, 'nih_alcohol_frequency', 0, 'Never');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (146, 'nih_alcohol_frequency', 1, 'Monthly Or Less');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (147, 'nih_alcohol_frequency', 2, 'Two To Four Times Per Month');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (148, 'nih_alcohol_frequency', 3, 'Two To Three Times Per Week');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (149, 'nih_alcohol_frequency', 4, 'Four Or More Times Per Week');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (150, 'nih_alcohol_frequency', 98, 'Don''t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (151, 'nih_alcohol_frequency', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (152, 'nih_asthma', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (153, 'nih_asthma', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (154, 'nih_asthma', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (155, 'nih_asthma', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (156, 'nih_asthma', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (157, 'nih_cancer', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (158, 'nih_cancer', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (159, 'nih_cancer', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (160, 'nih_cancer', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (161, 'nih_cancer', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (162, 'nih_cancer_active_treatment', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (163, 'nih_cancer_active_treatment', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (164, 'nih_cancer_active_treatment', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (165, 'nih_cancer_active_treatment', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (166, 'nih_cancer_active_treatment', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (167, 'nih_cancer_past_yr', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (168, 'nih_cancer_past_yr', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (169, 'nih_cancer_past_yr', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (170, 'nih_cancer_past_yr', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (171, 'nih_cancer_past_yr', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (172, 'nih_cardiovascular_disease', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (173, 'nih_cardiovascular_disease', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (174, 'nih_cardiovascular_disease', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (175, 'nih_cardiovascular_disease', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (176, 'nih_cardiovascular_disease', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (177, 'nih_serious_mental_illness', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (178, 'nih_serious_mental_illness', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (179, 'nih_serious_mental_illness', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (180, 'nih_serious_mental_illness', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (181, 'nih_serious_mental_illness', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (182, 'nih_chronic_kidney_disease', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (183, 'nih_chronic_kidney_disease', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (184, 'nih_chronic_kidney_disease', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (185, 'nih_chronic_kidney_disease', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (186, 'nih_chronic_kidney_disease', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (187, 'nih_chronic_kidney_disease_treatment', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (188, 'nih_chronic_kidney_disease_treatment', 1, 'Yes, But Not On Dialysis');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (189, 'nih_chronic_kidney_disease_treatment', 2, 'Yes And On Dialysis');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (190, 'nih_chronic_kidney_disease_treatment', 3, 'Yes, I''ve Had A Kidney Transplant And My Kidney Function Is Now Normal');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (191, 'nih_chronic_kidney_disease_treatment', 77, 'Don''t Know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (192, 'nih_chronic_lung_disease', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (193, 'nih_chronic_lung_disease', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (194, 'nih_chronic_lung_disease', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (195, 'nih_chronic_lung_disease', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (196, 'nih_chronic_lung_disease', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (197, 'nih_diabetes', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (198, 'nih_diabetes', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (199, 'nih_diabetes', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (200, 'nih_diabetes', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (201, 'nih_diabetes', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (202, 'nih_hypertension', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (203, 'nih_hypertension', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (204, 'nih_hypertension', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (205, 'nih_hypertension', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (206, 'nih_hypertension', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (207, 'nih_immunosuppressive_condition', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (208, 'nih_immunosuppressive_condition', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (209, 'nih_immunosuppressive_condition', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (210, 'nih_immunosuppressive_condition', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (211, 'nih_immunosuppressive_condition', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (212, 'nih_mental_health_disorder', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (213, 'nih_mental_health_disorder', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (214, 'nih_mental_health_disorder', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (215, 'nih_mental_health_disorder', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (216, 'nih_mental_health_disorder', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (217, 'nih_sickle_cell_disease', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (218, 'nih_sickle_cell_disease', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (219, 'nih_sickle_cell_disease', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (220, 'nih_sickle_cell_disease', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (221, 'nih_sickle_cell_disease', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (222, 'nih_pregnancy', 0, 'Not Pregnant');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (223, 'nih_pregnancy', 1, 'Pregnant');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (224, 'nih_pregnancy', 98, 'Don''t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (225, 'nih_pregnancy', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (226, 'nih_immunocompromised', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (227, 'nih_immunocompromised', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (228, 'nih_immunocompromised', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (229, 'nih_immunocompromised', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (230, 'nih_immunocompromised', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (231, 'nih_autoimm', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (232, 'nih_autoimm', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (233, 'nih_autoimm', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (234, 'nih_autoimm', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (235, 'nih_autoimm', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (236, 'nih_copd', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (237, 'nih_copd', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (238, 'nih_copd', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (239, 'nih_copd', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (240, 'nih_copd', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (241, 'nih_chronic_lung', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (242, 'nih_chronic_lung', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (243, 'nih_chronic_lung', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (244, 'nih_chronic_lung', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (245, 'nih_chronic_lung', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (246, 'nih_depression', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (247, 'nih_depression', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (248, 'nih_depression', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (249, 'nih_depression', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (250, 'nih_depression', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (251, 'nih_alc_sub_abuse', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (252, 'nih_alc_sub_abuse', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (253, 'nih_alc_sub_abuse', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (254, 'nih_alc_sub_abuse', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (255, 'nih_alc_sub_abuse', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (256, 'nih_iv_drug_use', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (257, 'nih_iv_drug_use', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (258, 'nih_iv_drug_use', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (259, 'nih_iv_drug_use', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (260, 'nih_iv_drug_use', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (261, 'nih_othermh', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (262, 'nih_othermh', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (263, 'nih_othermh', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (264, 'nih_othermh', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (265, 'nih_othermh', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (266, 'nih_other_chronic_cond', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (267, 'nih_other_chronic_cond', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (268, 'nih_other_chronic_cond', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (269, 'nih_other_chronic_cond', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (270, 'nih_other_chronic_cond', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (271, 'nih_coronary_artery_disease', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (272, 'nih_coronary_artery_disease', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (273, 'nih_coronary_artery_disease', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (274, 'nih_coronary_artery_disease', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (275, 'nih_coronary_artery_disease', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (276, 'nih_coronary_artery_disease_angina', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (277, 'nih_coronary_artery_disease_angina', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (278, 'nih_coronary_artery_disease_angina', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (279, 'nih_coronary_artery_disease_angina', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (280, 'nih_coronary_artery_disease_angina', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (281, 'nih_heart_attack', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (282, 'nih_heart_attack', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (283, 'nih_heart_attack', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (284, 'nih_heart_attack', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (285, 'nih_heart_attack', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (286, 'nih_chf', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (287, 'nih_chf', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (288, 'nih_chf', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (289, 'nih_chf', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (290, 'nih_chf', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (291, 'nih_stroke', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (292, 'nih_stroke', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (293, 'nih_stroke', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (294, 'nih_stroke', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (295, 'nih_stroke', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (296, 'nih_immunodeficiency', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (297, 'nih_immunodeficiency', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (298, 'nih_immunodeficiency', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (299, 'nih_immunodeficiency', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (300, 'nih_immunodeficiency', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (301, 'nih_hiv', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (302, 'nih_hiv', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (303, 'nih_hiv', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (304, 'nih_hiv', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (305, 'nih_hiv', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (306, 'nih_arrhythmia', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (307, 'nih_arrhythmia', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (308, 'nih_arrhythmia', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (309, 'nih_arrhythmia', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (310, 'nih_arrhythmia', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (311, 'nih_anemia', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (312, 'nih_anemia', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (313, 'nih_anemia', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (314, 'nih_anemia', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (315, 'nih_anemia', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (316, 'nih_premature_birth', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (317, 'nih_premature_birth', 1, 'Yes, Between 32 - 37 Weeks');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (318, 'nih_premature_birth', 2, 'Yes, Between 28-32 Weeks');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (319, 'nih_premature_birth', 3, 'Yes, Less Than 28 Weeks');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (320, 'nih_premature_birth', 4, 'Yes, But Not Sure How Many Weeks');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (321, 'nih_premature_birth', 77, 'Dont Know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (322, 'nih_chd', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (323, 'nih_chd', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (324, 'nih_chd', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (325, 'nih_chd', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (326, 'nih_chd', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (327, 'nih_cf', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (328, 'nih_cf', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (329, 'nih_cf', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (330, 'nih_cf', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (331, 'nih_cf', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (332, 'nih_cld_bpd', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (333, 'nih_cld_bpd', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (334, 'nih_cld_bpd', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (335, 'nih_cld_bpd', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (336, 'nih_cld_bpd', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (337, 'nih_copd_plus', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (338, 'nih_copd_plus', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (339, 'nih_copd_plus', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (340, 'nih_copd_plus', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (341, 'nih_copd_plus', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (342, 'nih_alz', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (343, 'nih_alz', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (344, 'nih_alz', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (345, 'nih_alz', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (346, 'nih_alz', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (347, 'nih_anxiety', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (348, 'nih_anxiety', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (349, 'nih_anxiety', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (350, 'nih_anxiety', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (351, 'nih_anxiety', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (352, 'nih_chronic_pain', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (353, 'nih_chronic_pain', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (354, 'nih_chronic_pain', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (355, 'nih_chronic_pain', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (356, 'nih_chronic_pain', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (357, 'nih_fibromyalgia', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (358, 'nih_fibromyalgia', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (359, 'nih_fibromyalgia', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (360, 'nih_fibromyalgia', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (361, 'nih_fibromyalgia', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (362, 'nih_gerd', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (363, 'nih_gerd', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (364, 'nih_gerd', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (365, 'nih_gerd', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (366, 'nih_gerd', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (367, 'nih_gestational_diabetes', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (368, 'nih_gestational_diabetes', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (369, 'nih_gestational_diabetes', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (370, 'nih_gestational_diabetes', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (371, 'nih_gestational_diabetes', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (372, 'nih_cholesterol', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (373, 'nih_cholesterol', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (374, 'nih_cholesterol', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (375, 'nih_cholesterol', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (376, 'nih_cholesterol', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (377, 'nih_thyroid', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (378, 'nih_thyroid', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (379, 'nih_thyroid', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (380, 'nih_thyroid', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (381, 'nih_thyroid', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (382, 'nih_immuno_compromised_solid_organ', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (383, 'nih_immuno_compromised_solid_organ', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (384, 'nih_immuno_compromised_solid_organ', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (385, 'nih_immuno_compromised_solid_organ', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (386, 'nih_immuno_compromised_solid_organ', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (387, 'nih_ibd', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (388, 'nih_ibd', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (389, 'nih_ibd', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (390, 'nih_ibd', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (391, 'nih_ibd', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (392, 'nih_insomnia', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (393, 'nih_insomnia', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (394, 'nih_insomnia', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (395, 'nih_insomnia', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (396, 'nih_insomnia', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (397, 'nih_ibs', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (398, 'nih_ibs', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (399, 'nih_ibs', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (400, 'nih_ibs', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (401, 'nih_ibs', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (402, 'nih_liver_disease', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (403, 'nih_liver_disease', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (404, 'nih_liver_disease', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (405, 'nih_liver_disease', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (406, 'nih_liver_disease', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (407, 'nih_lupus', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (408, 'nih_lupus', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (409, 'nih_lupus', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (410, 'nih_lupus', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (411, 'nih_lupus', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (412, 'nih_migraines', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (413, 'nih_migraines', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (414, 'nih_migraines', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (415, 'nih_migraines', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (416, 'nih_migraines', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (417, 'nih_ms', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (418, 'nih_ms', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (419, 'nih_ms', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (420, 'nih_ms', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (421, 'nih_ms', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (422, 'nih_neurodegenerative', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (423, 'nih_neurodegenerative', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (424, 'nih_neurodegenerative', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (425, 'nih_neurodegenerative', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (426, 'nih_neurodegenerative', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (427, 'nih_neurological_condition', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (428, 'nih_neurological_condition', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (429, 'nih_neurological_condition', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (430, 'nih_neurological_condition', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (431, 'nih_neurological_condition', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (432, 'nih_no_chronic_condition', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (433, 'nih_no_chronic_condition', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (434, 'nih_no_chronic_condition', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (435, 'nih_no_chronic_condition', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (436, 'nih_no_chronic_condition', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (437, 'nih_obesity', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (438, 'nih_obesity', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (439, 'nih_obesity', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (440, 'nih_obesity', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (441, 'nih_obesity', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (442, 'nih_osteoporosis', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (443, 'nih_osteoporosis', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (444, 'nih_osteoporosis', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (445, 'nih_osteoporosis', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (446, 'nih_osteoporosis', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (447, 'nih_pcos', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (448, 'nih_pcos', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (449, 'nih_pcos', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (450, 'nih_pcos', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (451, 'nih_pcos', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (452, 'nih_psoriasis', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (453, 'nih_psoriasis', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (454, 'nih_psoriasis', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (455, 'nih_psoriasis', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (456, 'nih_psoriasis', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (457, 'nih_renal', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (458, 'nih_renal', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (459, 'nih_renal', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (460, 'nih_renal', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (461, 'nih_renal', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (462, 'nih_rls', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (463, 'nih_rls', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (464, 'nih_rls', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (465, 'nih_rls', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (466, 'nih_rls', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (467, 'nih_ra', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (468, 'nih_ra', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (469, 'nih_ra', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (470, 'nih_ra', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (471, 'nih_ra', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (472, 'nih_seasonal_allergies', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (473, 'nih_seasonal_allergies', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (474, 'nih_seasonal_allergies', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (475, 'nih_seasonal_allergies', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (476, 'nih_seasonal_allergies', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (477, 'nih_heart_condition', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (478, 'nih_heart_condition', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (479, 'nih_heart_condition', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (480, 'nih_heart_condition', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (481, 'nih_heart_condition', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (482, 'nih_sleep_apnea', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (483, 'nih_sleep_apnea', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (484, 'nih_sleep_apnea', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (485, 'nih_sleep_apnea', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (486, 'nih_sleep_apnea', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (487, 'nih_substance_use', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (488, 'nih_substance_use', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (489, 'nih_substance_use', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (490, 'nih_substance_use', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (491, 'nih_substance_use', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (492, 'nih_thalassemia', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (493, 'nih_thalassemia', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (494, 'nih_thalassemia', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (495, 'nih_thalassemia', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (496, 'nih_thalassemia', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (497, 'nih_t1d', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (498, 'nih_t1d', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (499, 'nih_t1d', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (500, 'nih_t1d', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (501, 'nih_t1d', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (502, 'nih_t2dm', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (503, 'nih_t2dm', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (504, 'nih_t2dm', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (505, 'nih_t2dm', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (506, 'nih_t2dm', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (507, 'nih_cough', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (508, 'nih_cough', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (509, 'nih_cough', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (510, 'nih_cough', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (511, 'nih_cough', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (512, 'nih_fever_chills', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (513, 'nih_fever_chills', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (514, 'nih_fever_chills', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (515, 'nih_fever_chills', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (516, 'nih_fever_chills', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (517, 'nih_diff_breath', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (518, 'nih_diff_breath', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (519, 'nih_diff_breath', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (520, 'nih_diff_breath', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (521, 'nih_diff_breath', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (522, 'nih_headache', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (523, 'nih_headache', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (524, 'nih_headache', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (525, 'nih_headache', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (526, 'nih_headache', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (527, 'nih_muscle_ache', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (528, 'nih_muscle_ache', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (529, 'nih_muscle_ache', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (530, 'nih_muscle_ache', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (531, 'nih_muscle_ache', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (532, 'nih_olfactory', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (533, 'nih_olfactory', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (534, 'nih_olfactory', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (535, 'nih_olfactory', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (536, 'nih_olfactory', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (537, 'nih_fatigue', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (538, 'nih_fatigue', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (539, 'nih_fatigue', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (540, 'nih_fatigue', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (541, 'nih_fatigue', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (542, 'nih_numb_extremities', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (543, 'nih_numb_extremities', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (544, 'nih_numb_extremities', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (545, 'nih_numb_extremities', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (546, 'nih_numb_extremities', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (547, 'nih_nausea_vomiting_diarrhea', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (548, 'nih_nausea_vomiting_diarrhea', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (549, 'nih_nausea_vomiting_diarrhea', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (550, 'nih_nausea_vomiting_diarrhea', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (551, 'nih_nausea_vomiting_diarrhea', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (552, 'nih_abdom_pain', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (553, 'nih_abdom_pain', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (554, 'nih_abdom_pain', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (555, 'nih_abdom_pain', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (556, 'nih_abdom_pain', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (557, 'nih_skin_rash', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (558, 'nih_skin_rash', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (559, 'nih_skin_rash', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (560, 'nih_skin_rash', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (561, 'nih_skin_rash', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (562, 'nih_conjunctivitis', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (563, 'nih_conjunctivitis', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (564, 'nih_conjunctivitis', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (565, 'nih_conjunctivitis', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (566, 'nih_conjunctivitis', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (567, 'nih_throat_congestion_nose', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (568, 'nih_throat_congestion_nose', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (569, 'nih_throat_congestion_nose', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (570, 'nih_throat_congestion_nose', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (571, 'nih_throat_congestion_nose', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (572, 'nih_red_eyes', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (573, 'nih_red_eyes', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (574, 'nih_red_eyes', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (575, 'nih_red_eyes', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (576, 'nih_red_eyes', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (577, 'nih_high_temp', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (578, 'nih_high_temp', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (579, 'nih_high_temp', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (580, 'nih_high_temp', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (581, 'nih_high_temp', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (582, 'nih_other_symp', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (583, 'nih_other_symp', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (584, 'nih_other_symp', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (585, 'nih_other_symp', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (586, 'nih_other_symp', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (587, 'nih_no_sympt', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (588, 'nih_no_sympt', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (589, 'nih_no_sympt', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (590, 'nih_no_sympt', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (591, 'nih_no_sympt', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (592, 'nih_wheezing', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (593, 'nih_wheezing', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (594, 'nih_wheezing', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (595, 'nih_wheezing', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (596, 'nih_wheezing', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (597, 'nih_blue_lips', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (598, 'nih_blue_lips', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (599, 'nih_blue_lips', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (600, 'nih_blue_lips', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (601, 'nih_blue_lips', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (602, 'nih_balance', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (603, 'nih_balance', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (604, 'nih_balance', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (605, 'nih_balance', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (606, 'nih_balance', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (607, 'nih_slurred_peech', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (608, 'nih_slurred_peech', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (609, 'nih_slurred_peech', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (610, 'nih_slurred_peech', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (611, 'nih_slurred_peech', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (612, 'nih_confusion', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (613, 'nih_confusion', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (614, 'nih_confusion', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (615, 'nih_confusion', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (616, 'nih_confusion', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (617, 'nih_neuro_shakes', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (618, 'nih_neuro_shakes', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (619, 'nih_neuro_shakes', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (620, 'nih_neuro_shakes', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (621, 'nih_neuro_shakes', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (622, 'nih_sweating', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (623, 'nih_sweating', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (624, 'nih_sweating', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (625, 'nih_sweating', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (626, 'nih_sweating', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (627, 'nih_seizures', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (628, 'nih_seizures', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (629, 'nih_seizures', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (630, 'nih_seizures', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (631, 'nih_seizures', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (632, 'nih_rash_toes', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (633, 'nih_rash_toes', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (634, 'nih_rash_toes', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (635, 'nih_rash_toes', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (636, 'nih_rash_toes', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (637, 'nih_appetite', 0, 'No');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (638, 'nih_appetite', 1, 'Yes');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (639, 'nih_appetite', 97, 'Other');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (640, 'nih_appetite', 98, 'Don’t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (641, 'nih_appetite', 99, 'Prefer not to answer');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (642, 'nih_health_status', 0, 'Excellent');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (643, 'nih_health_status', 1, 'Very Good');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (644, 'nih_health_status', 2, 'Good');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (645, 'nih_health_status', 3, 'Fair');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (646, 'nih_health_status', 4, 'Poor');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (647, 'nih_health_status', 98, 'Don''t know');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (648, 'nih_health_status', 99, 'Prefer not to state');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (649, 'nih_height_category', 1, '5''1" - 5''6"');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (650, 'nih_height_category', 2, '5''7"-5''11"');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (651, 'nih_height_category', 3, '6'' and over');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (652, 'nih_weight_category', 1, '100-150');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (653, 'nih_weight_category', 2, '151-200');
INSERT INTO public.lkup_core_variable_permissible_value (id, variable_name, value, label) VALUES (654, 'nih_weight_category', 3, 'over 200');


--
